<?php

/**
 * @package zsUtilPlugin
 * @subpackage zsThumb
 */
class zsThumbConfigHandler extends sfYamlConfigHandler
{
  public function execute($configFiles)
  {
    // Parse the yaml
    $config = $this->parseYamls($configFiles);
    $strConfig = var_export($config, true);
    $data = <<<EOF
<?php
// auto-generated by %s
// date: %s
return $strConfig;
EOF;
    $data = sprintf($data, __CLASS__, date('Y/m/d H:i:s'));

    return $data;
  }


  /**
   * Returns size parameters
   *
   * @param string $size The size to get
   * @return mixed
   */
  public static function getSize($size)
  {
    $thumbnails = include sfContext::getInstance()->getConfigCache()->checkConfig('config/thumbnails.yml');

    if (!array_key_exists('sizes', $thumbnails))
      throw new Exception('No sizes set in thumbnails.yml');

    if (!array_key_exists($size, $thumbnails['sizes']))
      throw new Exception(sprintf('The size "%s" is not setup in thumbnails.yml', $size));

    return $thumbnails['sizes'][$size];
  }
}