all:
  # Required for zsThumb
  sfImageTransformPlugin:
    mime_type:
      auto_detect: true

  zsUtilPlugin:
    zsThumb:
      enabled:        false
      delete_with_cc: false
    zsSearch:
      max_results:    20
